version: 2.1

commands:
  command_example:
    parameters:
      aaa:
        type: integer
        default: 20
    environment:
      AAA: << parameters.aaa >>
    steps:
      - checkout
      - when:
          condition:
            equal: [ 10, << parameters.aaa >> ]
          steps:
            - run: echo 'hit!'

      - run:
          name: make directory
          command: echo ${AAA}

jobs:
  sample:
    docker:
      - image: debian:10
    steps:
      - checkout
      - when:
          condition:
            matches:
              value: << pipeline.git.branch >>
              pattern: /^.+$/
          steps:
            - run: echo 'hit!'

      - run:
          name: make directory
          command: |
            echo 'hello'
      - command_example:
          aaa: 10

workflows:
  version: 2
  welcome:
    jobs:
      - sample
