version: 2.1

jobs:
  sample:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: make directory
          command: | 
            echo 'hello'

workflows:
  welcome:
    jobs:
      - sample
