version: 2.1

parameters:
  make_and_upload_data:
    type: boolean
    default: false

jobs:
  sample:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: make directory
          command: | 
            echo 'hello'

workflows:
  welcome:
    when:
      equal: [false, << pipeline.parameters.make_and_upload_data >>]
    jobs:
      - sample
