version: 2.1

commands:
  command_example:
    parameters:
      aaa:
        type: integer
        default: 20
    steps:
      - checkout
      - when:
          condition:
            equal: [ 10, << parameters.aaa >> ]
          steps:
            - run: echo 'hit!'

      - run:
          name: make directory
          command: echo << parameters.aaa >>

jobs:
  sample:
    docker:
      - image: debian:10
    parameters:
      bbb:
        type: integer
        default: 20
    steps:
      - checkout
      - when:
          condition:
            matches:
              value: << pipeline.git.branch >>
              pattern: /^.+$/
          steps:
            - run: echo 'hit!'

      - run:
          name: make directory
          command: |
            echo 'hello'
      - command_example:
          aaa: << parameters.bbb >>

      # print env
      - run:
          name: export
          command: |
            export AAA="aaa"
            echo ${AAA}
      - run:
          name: print export
          command: echo ${AAA}

workflows:
  version: 2
  welcome:
    jobs:
      - sample:
          bbb: 10
