version: 2.1

jobs:
  sample:
    docker:
      - image: debian:10
    steps:
      - checkout
      - run:
          name: make directory
          when:
            matches:
              value: << pipeline.git.branch >>
              pattern: /^.+$/
          command: |
            echo 'hello'

workflows:
  version: 2
  welcome:
    jobs:
      - sample
