version: 2.1

parameters:
  aaa:
    type: integer
    default: 20

# commands:
#   command_example:
#     environment:
#       AAA: << pipeline.parameters.aaa >>
#     steps:
#       - checkout
#       - when:
#           condition:
#             equal: [ 10, << pipeline.parameters.aaa >> ]
#           steps:
#             - run: echo 'hit!'

#       - run:
#           name: make directory
#           command: echo ${AAA}

jobs:
  sample:
    docker:
      - image: debian:10
    aaa: 10
    steps:
      - checkout
      - when:
          condition:
            matches:
              value: << pipeline.git.branch >>
              pattern: /^.+$/
          steps:
            - run: echo 'hit!'

      - run:
          name: make directory
          command: |
            echo 'hello'
      # - command_example

workflows:
  version: 2
  welcome:
    jobs:
      - sample
